"""Configuration settings"""

# Camera settings
CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30

# Hand tracking settings
MAX_NUM_HANDS = 2
MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7

# Mouse control settings
SMOOTHING_FACTOR = 0.5
MOUSE_SPEED_MULTIPLIER = 1.5
SCREEN_PADDING = 100

# Gesture settings - Left hand
SINGLE_CLICK_THRESHOLD = 40.0
SINGLE_CLICK_MAX_TIME = 0.25
DOUBLE_CLICK_THRESHOLD = 40.0
COPY_THRESHOLD = 40.0
PASTE_THRESHOLD = 40.0

# Gesture settings - Right hand scroll
SCROLL_UP_THRESHOLD = 45.0
SCROLL_DOWN_THRESHOLD = 45.0
SCROLL_SPEED = 15
SCROLL_SMOOTHING_FRAMES = 5

# Gesture settings - Desktop switching
DESKTOP_SWITCH_THRESHOLD = 40.0

# Gesture settings - Drag mode
DRAG_START_THRESHOLD = 40.0
DRAG_END_THRESHOLD = 40.0

# Visual settings
SHOW_LANDMARKS = True
SHOW_FPS = True